### PR TITLE
Update Alendaur to 0.3 [D]

### PR DESCRIPTION
**Pull request by flohlen**
Ignore the both revert commits, I accidently hit revert.

Added/completed map.yml
Added screenshots 0.3 [D]
Completed the map:
- both sides are the same:
- the castle is now on both sides
- both castles are connected with a bridge that spans over the middle

And I would like to ask for permissions to submit the map on the Avicus Forums.

### CODE REVIEW

**Comment by ViceWatercolour** [comment]
@KyloCode also has a repo for this -- not sure where it's at, but I'll gladly merge it if Kylo is fine with it.

**Comment by thekeenant** [comment]
ayy ok

**Comment by flohlen** [comment]
Does that also means I can post the map on the forums?

**Comment by ViceWatercolour** [comment]
I suppose

**Comment by flohlen** [comment]
Forum Thread: https://avicus.net/forums/f3532922b

**Pull request merged**
